Fix "Multiple top-level packages discovered in a flat-layout" error
Since setuptools 61.1.0 [1], building and installing edmp-image-builder is
failing with error:

error: Multiple top-level packages discovered in a flat-layout: ['dib', 'images'].

Note that edpm-image-builder does not contains any actual python module
but it's just python install tooling for convenience.

[1] https://setuptools.pypa.io/en/latest/history.html#v61-1-0